pipeline:
    name: javaspringbootpipeline
    identifier: javaspringbootpipeline
    allowStageExecutions: true
    projectIdentifier: Demo_Project
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.gitconnector
                repoName: java
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: harnessaks
                          namespace: default
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: building code
                                identifier: building_code
                                spec:
                                    connectorRef: Jfrog_harness_integration
                                    image: harnessdev.jfrog.io/default-docker-remote/maven:latest
                                    command: |
                                        mvn --version
                                        echo '<+secrets.getValue("account.maven_settings_xml")>' > settings.xml
                                        mvn clean package -s settings.xml
                          - parallel:
                                - step:
                                      type: BuildAndPushDockerRegistry
                                      name: building and pushing
                                      identifier: building_and_pushing
                                      spec:
                                          connectorRef: Jfrog_harness_integration
                                          repo: harnessdev.jfrog.io/docker-local/javasprongboot
                                          tags:
                                              - javaimageversion-<+pipeline.sequenceId>
                                - step:
                                      type: ArtifactoryUpload
                                      name: upload artifact
                                      identifier: upload_artifact
                                      spec:
                                          connectorRef: artifactory
                                          target: lib/
                                          sourcePath: /harness/target/*.jar
        - stage:
              name: approval
              identifier: dev_approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approval
                                identifier: approval
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.dev_approval
                                    approverInputs: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: Abort
        - stage:
              name: deploy
              identifier: deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: Dev
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: Jfrog_harness_integration
                                          imagePath: docker-local/javasprongboot
                                          tag: javaimageversion-<+pipeline.sequenceId>
                                      type: DockerRegistry
                              manifests:
                                  - manifest:
                                        identifier: deployment
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.gitconnector
                                                    gitFetchType: Branch
                                                    paths:
                                                        - deployment.yaml
                                                    repoName: java
                                                    branch: master
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.gitconnector
                                                    gitFetchType: Branch
                                                    paths:
                                                        - values.yaml
                                                    repoName: java
                                                    branch: master
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.AKSConnector
                              namespace: harnessdemo
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
              variables: []
